# Generated by Django 3.0.6 on 2020-05-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turnkey',
            fields=[
                ('project_ID', models.AutoField(primary_key=True, serialize=False)),
                ('turnkey_projet_Name', models.CharField(max_length=200)),
                ('region', models.IntegerField(choices=[(1, 'Arab'), (2, 'Afrika'), (3, 'Asia'), (4, 'Europa'), (5, 'America')], default=None)),
                ('project_total_volume', models.DecimalField(decimal_places=4, max_digits=10)),
                ('number_trains', models.IntegerField()),
                ('number_cars_per_train', models.IntegerField()),
                ('money', models.IntegerField()),
                ('cost_per_car', models.DecimalField(decimal_places=4, max_digits=10)),
                ('track_length', models.DecimalField(decimal_places=4, max_digits=10)),
                ('number_station', models.IntegerField()),
                ('cost_station', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cost_per_KM', models.DecimalField(decimal_places=4, max_digits=10)),
                ('country', models.TextField()),
                ('project_start_date', models.DateTimeField()),
                ('project_end_date', models.DateTimeField()),
            ],
        ),
    ]
