# Generated by Django 3.0.6 on 2020-06-09 16:26

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuerzel', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_in_SAM', models.BooleanField(default=False, null=True)),
                ('data_source', models.CharField(max_length=500, null=True)),
                ('project_category', models.CharField(max_length=500, null=True)),
                ('comment_region', models.CharField(max_length=500, null=True)),
                ('winner_em', models.CharField(max_length=500, null=True)),
                ('competitiveness', models.CharField(max_length=500, null=True)),
                ('oas_competition_score', models.FloatField(null=True)),
                ('oas_financial_attractiveness', models.FloatField(null=True)),
                ('power', models.FloatField(null=True)),
                ('news', models.CharField(max_length=500, null=True)),
                ('name', models.CharField(max_length=500, null=True)),
                ('region', models.IntegerField(choices=[(0, 'North-East-Europe'), (1, 'South-West-Europe'), (2, 'Latin America'), (3, 'Asia-Pacific'), (4, 'Middle East & Africa'), (5, 'North America'), (6, 'China'), (7, 'UK & Ireland')], default=None, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('city', models.CharField(max_length=500, null=True)),
                ('type_of_business', models.IntegerField(choices=[(0, 'LRT'), (1, 'Metro'), (2, 'Monorail/VAL'), (3, 'Rail HSP'), (4, 'Rail ML/Commuter')], default=None, null=True)),
                ('type_of_project', models.CharField(max_length=500, null=True)),
                ('fy_of_award', models.FloatField(default=0.0, null=True)),
                ('oi_date', models.FloatField(default=0.0, null=True)),
                ('project_end_date', models.FloatField(default=0.0, null=True)),
                ('number_trains', models.PositiveIntegerField(default=0, null=True)),
                ('number_cars_per_train', models.PositiveIntegerField(default=0, null=True)),
                ('cost_per_car', models.FloatField(default=0.0, null=True)),
                ('track_length', models.FloatField(default=0.0, null=True)),
                ('number_station', models.PositiveIntegerField(default=0, null=True)),
                ('number_depots', models.PositiveIntegerField(default=0, null=True)),
                ('realization_probability', models.FloatField(null=True)),
                ('order_probability', models.FloatField(null=True)),
                ('total_project_volume', models.FloatField(null=True)),
                ('source', models.CharField(max_length=500, null=True)),
                ('no_stratigic_fit_not_mandated', models.BooleanField(default=False, null=True)),
                ('no_bid_political_positioning', models.BooleanField(default=False, null=True)),
                ('no_bid_consortium_incl_civil', models.BooleanField(default=False, null=True)),
                ('no_bid_rolling_stock', models.BooleanField(default=False, null=True)),
                ('no_bid_target_price', models.BooleanField(default=False, null=True)),
                ('no_bid_risk_profile', models.BooleanField(default=False, null=True)),
                ('comment_bid', models.CharField(max_length=1000, null=True)),
                ('disqualified', models.BooleanField(default=False, null=True)),
                ('lost', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country')),
            ],
        ),
    ]
